builds:
  - binary: postfix_exporter
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: ryuichi1208
    name: postfix_exporter
